server:
  port: 8808
spring:
  application:
    name: mp
  datasource:
    url: jdbc:oracle:thin:@192.168.0.215:1521:orcl
    username: HENAN_RTDB
    password: HENAN_RTDB
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,logging
      initial-size: 8
      min-idle: 3
      max-active: 10
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle:  true
      test-on-borrow: false
      test-on-return: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
